[color.theme]
red=#f44336
pink=#e91e63
purple=#9c26b0
deep-purple=#673ab7
indigo=#3f51b5
blue=#2196f3
light-blue=#03a9f4
cyan=#00bcd4
teal=#009688
green=#4caf50
light-green=#8bc34a
lime=#cddc39
yellow=#ffeb3b
amber=#ffc107
orange=#ff9800
deep-orange=#ff5722
brown=#795548
grey=#9e9e9e
blue-grey=#607d8b
[color]
foreground = #ECEFF1
background = #263238
color0     = #37474F
color1     = #F44336
color2     = #4CAF50
color3     = #FFEB3B
color4     = #2196F3
color5     = #9C27B0
color6     = #00BCD4
color7     = #90A4AE
color8     = #546E7A
color9     = #FF8961
color10    = #80E37E
color11    = #FFFF72
color12    = #6EC6FF
color13    = #D05CD3
color14    = #62EFFF
color15    = #CFD8DC

[window]
padding=5
border=1
border_color=${color.color4}


[font]
name = Fira Code
pt = 12
